# Generated by Django 5.0 on 2026-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station", models.CharField(max_length=100)),
                ("hour", models.IntegerField()),
                ("day_of_week", models.IntegerField()),
                ("passengers", models.IntegerField()),
                ("is_peak", models.BooleanField(default=False)),
                ("is_weekend", models.BooleanField(default=False)),
                ("actual_crowd", models.IntegerField()),
                (
                    "bucket",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="PredictionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station", models.CharField(max_length=100)),
                ("hour", models.IntegerField()),
                ("day", models.IntegerField()),
                ("pred_bucket", models.CharField(max_length=10)),
                ("pred_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
