// frontend/src/pages/WeeklyDigest.jsx
import { useState, useEffect } from 'react';
import GlassCard from '../components/common/GlassCard';
import StatCard from '../components/common/StatCard';
import LoadingSpinner from '../components/common/LoadingSpinner';
import { getWeeklyDigest } from '../api/analytics.api';
import { formatCurrency } from '../utils/formatters';

export default function WeeklyDigest() {
  const [digest, setDigest] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetch = async () => {
      try {
        const res = await getWeeklyDigest();
        setDigest(res.data.digest);
      } catch (err) { console.error(err); }
      finally { setLoading(false); }
    };
    fetch();
  }, []);

  if (loading) return <div className="page"><LoadingSpinner /></div>;

  return (
    <div className="page">
      <div className="page-header">
        <h1 className="page-title">Weekly Digest 🤖</h1>
        <p className="page-subtitle">AI-powered trip summary for the past 7 days</p>
      </div>

      {digest ? (
        <>
          <div className="grid grid-4" style={{ marginBottom: 'var(--space-xl)' }}>
            <StatCard icon="🎫" value={digest.totalTrips} label="Trips This Week" />
            <StatCard icon="💰" value={formatCurrency(digest.totalSpent)} label="Total Spent" color="#ef4444" />
            <StatCard icon="📏" value={`${digest.totalDistance} km`} label="Distance Covered" color="#3b82f6" />
            <StatCard icon="🌿" value={`${digest.totalCO2Saved} kg`} label="CO₂ Saved" color="#22c55e" />
          </div>

          <div className="grid grid-2">
            <GlassCard style={{ padding: '24px' }}>
              <h3 style={{ fontFamily: 'var(--font-display)', fontWeight: 600, marginBottom: '16px' }}>🛤️ Top Route</h3>
              {digest.topRoute ? (
                <div>
                  <p style={{ fontSize: '1.2rem', fontWeight: 600 }}>{digest.topRoute.route}</p>
                  <p style={{ color: 'var(--text-secondary)', marginTop: '4px' }}>
                    Taken {digest.topRoute.count} time{digest.topRoute.count > 1 ? 's' : ''} this week
                  </p>
                </div>
              ) : (
                <p style={{ color: 'var(--text-muted)' }}>No routes this week</p>
              )}
            </GlassCard>

            <GlassCard style={{ padding: '24px' }}>
              <h3 style={{ fontFamily: 'var(--font-display)', fontWeight: 600, marginBottom: '16px' }}>⏰ Peak vs Off-Peak</h3>
              <div style={{ display: 'flex', gap: '20px' }}>
                <div style={{ textAlign: 'center', flex: 1 }}>
                  <p style={{ fontSize: '2rem', fontWeight: 700, fontFamily: 'var(--font-display)', color: 'var(--warning)' }}>
                    {digest.peakTrips}
                  </p>
                  <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>Peak Trips</p>
                </div>
                <div style={{ textAlign: 'center', flex: 1 }}>
                  <p style={{ fontSize: '2rem', fontWeight: 700, fontFamily: 'var(--font-display)', color: 'var(--success)' }}>
                    {digest.offPeakTrips}
                  </p>
                  <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>Off-Peak Trips</p>
                </div>
              </div>
            </GlassCard>
          </div>

          <GlassCard style={{ marginTop: 'var(--space-xl)', padding: '24px' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px', flexWrap: 'wrap', gap: '8px' }}>
              <h3 style={{ fontFamily: 'var(--font-display)', fontWeight: 600, margin: 0 }}>✨ AI Insight</h3>
              {digest.aiGenerated && (
                <span style={{
                  display: 'inline-flex', alignItems: 'center', gap: '4px',
                  fontSize: '0.7rem', fontWeight: 700, color: '#6366f1',
                  background: 'rgba(99,102,241,0.1)', border: '1px solid rgba(99,102,241,0.25)',
                  padding: '3px 10px', borderRadius: '20px', letterSpacing: '0.04em',
                }}>
                  <span style={{ fontSize: '10px' }}>✦</span> Generated by Gemini AI
                </span>
              )}
            </div>
            <p style={{ color: 'var(--text-secondary)', lineHeight: 1.75, margin: 0, fontSize: '0.975rem' }}>
              {digest.aiSummary
                || (digest.totalTrips > 0
                  ? `Great week! You averaged ${formatCurrency(digest.avgFarePerTrip)} per trip across ${digest.totalTrips} rides.`
                  : 'No trips recorded this week. Book a ride to see your weekly insights!')}
            </p>
          </GlassCard>
        </>
      ) : (
        <GlassCard style={{ padding: '60px', textAlign: 'center' }}>
          <span style={{ fontSize: '3rem' }}>🤖</span>
          <p style={{ color: 'var(--text-secondary)', marginTop: '12px' }}>No trip data for this week yet</p>
        </GlassCard>
      )}
    </div>
  );
}
