# Generated by Django 5.0 on 2026-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyAnalyticsSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_bookings", models.IntegerField(default=0)),
                ("peak_station", models.CharField(default="", max_length=100)),
                ("avg_passengers", models.FloatField(default=0)),
                ("total_co2_saved", models.FloatField(default=0)),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Daily analytics summaries",
                "ordering": ["-date"],
            },
        ),
    ]
